version: "3.7"
services:
  app:
    build:
      # args:
      #   user: deploy
      #   uid: 1000
      context: ./docker/
      dockerfile: Dockerfile
    # image: explore-vietnam
    container_name: explore-vietnam-app
    restart: unless-stopped
    working_dir: /var/www/explore-vietnam
    volumes:
      - ./:/var/www/explore-vietnam/
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: explore-vietnam-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  # nginx:
  #   image: nginx:alpine
  #   container_name: explore-vietnam-nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/:/etc/nginx/conf.d/
  #   networks:
  #     - explore-vietnam

volumes:
  app_data:
  db_data: